language: rust

cache:
  directories:
    - $HOME/.cargo

addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - gcc-5
        - libarchive-dev
        - pkgconf

before_install: . ./ci/before_install.sh
